### PR TITLE
Created an RPM .spec file

### PR DESCRIPTION
**Pull request by AxelSilverdew**
### I've also added a link to a copr repo that I'm maintaining for nvidia-xrun for Fedora 27+

### CODE REVIEW

**Comment by Witko** [comment]
Hi @AxelSilverdew ,
thank you for your work. Would it be possible to have the fedora specific files outside of this repo?
As for the AUR i've put all the arch specific stuff in AUR repo.
Thx!

**Comment by AxelSilverdew** [comment]
@Witko, You mean the RPMs?
Yeah, those can be removed from the repo.
I'd keep the spec file in the repo though, is that okay?

**Comment by Witko** [comment]
Hi @AxelSilverdew ,
i'm not aware how it works with fedora packages - but ideally the spec goes elsewhere. If this is not doable im fine with it being here - but please put it into a fedora dir

**Comment by AxelSilverdew** [comment]
@Witko Okay, I'll do that.
I'll put it into an `rpm-spec` folder.

**Comment by AxelSilverdew** [comment]
@Witko is this okay now?

**Pull request merged**
