### PR TITLE
Merge nvidia-xrun-pm into nvidia-xrun

### PR DESCRIPTION
**Pull request by michelesr**
This PR merges all the changes introduced in nvidia-xrun-pm into nvidia-xrun, in particular:

- the systemd service that takes care of turning off the GPU automatically at boot (if enabled)
- in order to fix problems described in #105 you need to handle two devices separately, the graphic card and the PCIe controller, which ids can be configured in `/etc/default/nvidia-xrun`

### CODE REVIEW

**Comment by Witko** [comment]
Hi @michelesr ,
did you test this?:) I can't atm.
Thanks for the effort!

**Comment by Witko** [comment]
Just thinking, maybe the turn off nvidia at boot should not be part of nvidia-xrun itself, maybe in different package it would make more sense. What do you think?

**Comment by michelesr** [comment]
It works fine on my machine and I think there are other users that are currently using my fork (expecially the ones running newer graphic cards, as they seems to have problems with bbswitch), as I can see from the conversations on different GitHub issues in nvidia-xun. 

@ekultails helped me with building the RPM spec for nvidia-xrun so maybe it can help updating the upstream rpm-spec as well: at the moment he is also maintaining the [COPR package](https://copr.fedorainfracloud.org/coprs/ekultails/nvidia-xrun-pm/) while I'm maintaining the [AUR package](https://aur.archlinux.org/packages/nvidia-xrun-pm/) for nvidia-xrun-pm.

IMHO it makes sense to keep the systemd service implementation here as it would make the job easier for package maintainers, also without it there's no way to automatically turn off the graphic card at boot, as bbswitch was doing that so I think it makes sense to provide this service as a replacement.

**Comment by Witko** [comment]
For me it would seem nice to have it as a separate package, list it as optional dependency. But for now lets keep it here.

**Pull request merged**
